### ISSUE TITLE
Governance. Referenda details. Incorrect layout

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#2028]
## Description

Layout for referenda details does not match with the mockups.

## Steps to Reproduce

1. Go to Governance page
2. Open any referenda with off-chain data

## Expected Behavior
- Description at the left sight
- Right sight contains 
  - Voting status
  - Summary
  - Additional
  - Timeline
  - Advanced

Example:
![image](https://github.com/user-attachments/assets/6b307929-7911-442e-b68a-065cc558d725)
https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov-voting?node-id=574-100443&t=TXEGPrZMAvD95RuI-4

## Actual Behavior
- Right column is a top tile
- Description with off-chain data at the bottom
<img width="1464" alt="Screenshot 2024-08-06 at 13 08 59" src="https://github.com/user-attachments/assets/c1cc831a-d8ec-4b4f-9dce-bc23250346f9">
<img width="1464" alt="Screenshot 2024-08-06 at 13 09 01" src="https://github.com/user-attachments/assets/8f5ecdc9-51bf-4c2d-9b11-0a96fe0cd7c4">

## Environment
https://github.com/novasamatech/nova-spektr/commit/74fb677ee2dd26a02c67eeb6860265cc9bea9add

**Comment by Tbaut** [comment]
I think this is fixed by https://github.com/novasamatech/nova-spektr/pull/2078#pullrequestreview-2234748853 as well. Please let me know if not.

**Comment by stepanLav** [comment]
Status verification: ❌

Still reproducible:

https://github.com/user-attachments/assets/d374bb35-7d0c-4369-97b1-496aa600493e

When open referenda details, detailed description goes down, while it should hold at the left side on the top

**Comment by Tbaut** [comment]
Hey @stepanLav, can you check this please? https://github.com/novasamatech/nova-spektr/pull/2274
This reduces the overall possible window size before the boxes change layout.

**Comment by stepanLav** [comment]
Status verification: ✅
